language: go
go:
  - 1.2
after_success:
  - make coverage
env:
  global:
    secure: MzN2mEspBQbQwiqLUSS6zagXTq6hnre5N+X4XyMqrlstmrNxJUycW6vGeoeDkbs/znr/BFfX7wezvnop7IlellEsEm8VV6t4taqajLpdWRsM0fjV0U7CDpdrdrBuQ+7cT+qpWkvF8i9TnjMEjG2veEz+THXllEI6Jt8w+KP9c6Y=
